### ISSUE TITLE
Please let we download binaries from GitHub

### ISSUE THREAD

**Issue by ghost** [intika/ungoogled-chromium-binaries#1]
I need a fixed link for my portage [ebuild](https://gitlab.com/chaoslab/chaoslab-overlay/tree/master/www-client/ungoogled-chromium-bin). Right now I have to following `SRC_URI`:

```
BASE_SRC_URI="https://dl.opendesktop.org/api/files/download/id"
SRC_URI="${BASE_SRC_URI}/1540555385/s/e061da5632443ee3e1a83a8e212c8300/t/1540642559/${MY_P}.tar.xz.tar.xz -> ${PN}-${MY_PV}.tar.xz"
```

But it keeps breaking the Manifest (file integration) check, as the URI from OpenDesktop generates a session ID.

So could you kindly upload to GitHub too, like you did before?

FYI chromium-70.0.3538.102 was released a few hours ago. 😉

**Comment by intika** [comment]
> FYI chromium-70.0.3538.102 was released a few hours ago.

Thanks for the info and the PR :) 

Opendesktop is used to pay the build server... 

I know arch based repos need a fixed link... Santoz is re-uploading the binary for its aur https://aur.archlinux.org/packages/ungoogled-chromium-bin/ ... 

But i just made a repo for that purpose ;) 

https://github.com/intika/uc-arch-binaries/releases

Hash is available on the main uc-binaries location ;)

**Comment by ghost** [comment]
> But i just made a repo for that purpose ;)

Much appreciated. 👍

**Comment by intika** [comment]
You are welcome, let me know if you need something else ;)

**Comment by intika** [comment]
i ll update it on new releases of course ;) if i make a build ;)
